Repository mrueg/addon-teddycloud, pull requests merged in 2025-01, with the labels that each got.

#14 Dockerfile: Update git package
  teddycloud/Dockerfile
Labels: dependencies

#13 bugfix: Add filter to download and play content
  teddycloud/rootfs/etc/nginx/servers/ingress.conf
Labels: bugfix

#19 New layout
  README.md
  teddycloud/Dockerfile
  teddycloud/rootfs/etc/s6-overlay/s6-rc.d/teddycloud/run
Labels: breaking-change

#20 Document MPD streaming
  README.md
Labels: documentation
